### ISSUE TITLE
Consider adding eslint-plugin-compat and eslint-plugin-ecmascript-compat

### ISSUE THREAD

**Issue by TKDev7** [rayxiom/rayxiom#68]
These should help with linting browser APIs

**Comment by so1ve** [comment]
Hi @MrHBS! Sorry for the late response.
Personally, I don't want to add these plugins into my eslint config - they require some extra configuration in each project, which cannot be used out-of-box. I don't have to worry about compatibility too (my projects are generally based on the latest versions of browsers and Node.js). If you are interested in my config, feel free to fork it :)

**Comment by TKDev7** [comment]
Got it
